export default [
  {
    id: '100',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'Logitech Keyboard',
    description: "Perfect stroke keys - spherical-dished keys match the shape of your fingertips, Offering satisfying feedback with every tap<BULLET>Comfort and stability - Type with confidence on a keyboard crafted for comfort, stability, and precision<BULLET>Smart illumination -hand proximity detection and automatic backlighting",
    vendor_location_id: '10',
    category: 'Computer',
    rating: '4.2',
    price:'149.99',
    deliveryFee:'0',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '101',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'SAITOR Webcam',
    description: "[1080P Full HD Webcam]Castries 1080P webcam supply crisp Image and crystal clear video at a fluid 30 frames/sec, and Automatic Light Correction and HDR technology let to auto adjust color and brightness. So you will get the most crisp and clear video calling experience in even dim light. Note: NO NIGHT VISION FUNCTION. <BULLET> [Plug and Play & Easy to Use ]USB driver and automatic installation, just Plug and Play with a USB 2.0 cable, system reads the hardware drive automatically no additional drivers or download software required. Adjustable universal clip fits to work with any laptop/desktop/Mac/PC,/LCD monitors and even other flat surfaces monitors, which is quick and easy to meet your variety of laptop or PC devices needs.<BULLET> [Update Webcam & Smooth Live Streaming]Web camera specifically designed with facial-enhancement technology, which makes you look best in recording, video calling, online teaching as well as gaming. Help you get excellent quality video on Skype, FaceTime, OBS, XBOX ONE, Hangouts, Facebook, Zoom, Twitch etc. instant messaging applications.<BULLET>[Built-in Noise Reduction Microphone]Built-in noise reduction microphone can automatically eliminate distracting background noise natural and clear sound and clearly capture sound within 5 meters when it working. Achieve real studio-quality sound, it becomes the best choice for video conference or recording.<BULLET>[Compatible With]USB port, widely works with multi-operations widely works Windows 7/8/10, Windows 2000, Windows XP, Mac OSX 10.7/, Mac OS X , Android TV and Android 4.0 or higher version operation systems. Internet connection, and it is is compatible with Skype, OBS, You Tube, Facebook, Twitter, WeChat, QQ etc instant messaging applications.",
    vendor_location_id: '10',
    category: 'Computer',
    rating: '3.9',
    price:'119.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '102',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'Nintendo Switch',
    description: "This Nintendo Switch system takes design inspiration from the New animal crossing: new horizons game, with lovely pastel green and Blue Joy-Con controllers that are white on the back, white wrist straps and a white Nintendo Switch Dock, adorned with images of recognizable characters Tom nook and nooklings Timmy and Tommy.<BULLET>Animal crossing Edition<BULLET>Animal crossing Edition Joy-Con controllers<BULLET>This Bundle includes the Nintendo Switch console and Nintendo Switch Dock in Black, with contrasting left and right Joy-Con Controllers",
    vendor_location_id: '10',
    category: 'Games',
    rating: '2.2',
    price:'399.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '103',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'Super Smash Bros',
    description: "Legendary game worlds and fighters collide in the ultimate showdown—a new entry in the Super Smash Bros. Series for the Nintendo Switch system! New fighters, like Inkling from the Splatoon series and Ridley from the Metroid series, make their Super Smash Bros. Series debut alongside every Super Smash Bros. Fighter in the series…EVER! Fast combat, new items, new attacks, new defensive options, and more will keep the battle raging whether you’re at home or on the go!.<BULLET>Elevate the Super Smash Bros. experience to new heights with faster combat<BULLET>Hold a 4 player free-for-all, or kick it up to 8-player battles<BULLET>All current Super Smash Bros. series amiibo figures are supported<BULLET>New fighters, new stages, and every fighter ever featured in the series…EVER!",
    vendor_location_id: '10',
    category: 'Games',
    rating: '4.6',
    price:'32.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '104',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'Hamilton Sandwich Maker',
    description: "Hamilton Beach 25490A Dual Breakfast Sandwich Maker<BULLET>Makes 1 to 2 sandwiches<BULLET>Ready in 5 minutes<BULLET>Cook delicious breakfast sandwiches in the comfort of your own home<BULLET>Use your own fresh ingredients, including eggs, cheese and much more<BULLET>Timer with audible tone; Quick and easy recipes included; Easy cleanup - all removable parts are dishwasher safe",
    vendor_location_id: '10',
    category: 'Appliances',
    rating: '3.8',
    price:'49.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '105',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'Baseball Pitching Machine',
    description: "The Franklin Sports MLB Youth Pitching Machine offers the fun and excitement of a baseball batting cage for young developing players. It's height adjustable and pitches Aero-Strike plastic balls at 10-second intervals. Set includes one pitching machine and 6 white Aero-Strike balls. Batteries not included.<BULLET>Height adjustment for pitches<BULLET>Franklin Sports MLB Electronic Pitching Machine<BULLET>Height adjustment for pitches<BULLET>Assembled height: 17.75inch X 9.5inch X 9.875inch",
    vendor_location_id: '10',
    category: 'Sports',
    rating: '3.6',
    price:'899.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '106',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'Soozier Kinetic Bike',
    description: 'SIN IN SILENCE: Smooth, seamless design and noise reduction resistance wheel mean you there’s no need to amp up the volume when you build up the burn, provides progressive resistance increases as the speed increases. NOTE: Not suit for MTB.<BULLET>STABLE CONSTRUCTION: Extra wide steel construction in superior strength, hold up to 300lbs.<BULLET>EASY SETUP: Hooks any bike including road or mountain bikes with 26-28 or 700CC wheels, do not fit a bike with quick release rear wheel<BULLET>PORTABLE: Folds down flat for easy indoor storage and transport<BULLET>Overall Dimensions: 21.4L x 18.6W x 15.5H, Resistance: Wind',
    vendor_location_id: '10',
    category: 'Sports',
    rating: '3.0',
    price:'279.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '107',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'Ring Fit Adventure',
    description: "Control in game movements with the new ring con and leg strap accessories<BULLET>Batteries : 1 Lithium ion batteries required.<BULLET>Language : English<BULLET>Rated : Everyone 10+<BULLET>Product Dimensions : 6.6 x 33.53 x 32.77 cm; 698.53 Grams<BULLET>Release date : Dec 11 2019<BULLET>Manufacturer : Nintendo<BULLET>Manufacturer contact : REDMOND, WA, 98052 US ASIN : B07XV4NHHN<BULLET>Item model number : HACRAL3PA<BULLET>Best Sellers Rank: #69 in Video Games (See Top 100 in Video Games)",
    vendor_location_id: '10',
    category: 'Books',
    rating: '5.0',
    price:'29.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '108',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'NBA 2K21 Standard Edition',
    description: "NBA 2K21 is the latest release in the world-renowned, best-selling NBA 2K series.<BULLET>MyCAREER - Embark on your own personal, cinematic basketball journey to reach your ultimate destination: the National Basketball Association.<BULLET>MyTEAM - Assemble your G.O.A.T. NBA fantasy team of current players and historic legends and compete against the world.<BULLET>NEIGHBORHOOD - Live out your virtual, day-to-day basketball life in a neighborhood that doesn’t sleep and that always offers something to do.",
    vendor_location_id: '10',
    category: 'Games',
    rating: '4.1',
    price:'69.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
  {
    id: '109',
    email: 'clearcarwash@gmail.com',
    password: '451632ygt123561f23tyu1283761g',
    name: 'Electric Surface Burner',
    description: 'It has a Y-bracket.<BULLET>It is a great replace for MP22YA Surface Burner Element.<BULLET>It is include 2 set 8inch Burner Element & 2 set 6inch Burner Element<BULLET>Material:Ferrochrome aluminum alloy<BULLET>Color:Dark green<BULLET>Part Number:MP22YA<BULLET>The smaller Element Size:18cm/7<BULLET>The larger Element Size:15cm/5.9<BULLET>Weight:1280g<BULLET>2 x Smaller Burner Element (6 inch)<BULLET>2 x Larger Burner Element (8 inch)',
    vendor_location_id: '10',
    category: 'Appliances',
    rating: '3.7',
    price:'399.99',
    deliveryFee:'20',
    discount:'5',
    quantity:1,
    vendor_banner_image: 'https://s25180.pcdn.co/wp-content/uploads/2017/11/iStock-834477888-Cover-STR-Image2.jpg',
    vendor_admin_access_token: 'fkjsdhakgudhdhi3kj4redf78re43yuh3ireof8tyug43j4krefg98r7ew',
    location: {
      location_id: '10',
      location_lat: '43.65189',
      location_long: '-79.38171',
      location_address_line_1: '220 Victoria Avenue',
      location_address_line_2: 'Scarborough',
      location_state: 'ON',
      location_postal_code: 'M1R 1H6',
    },
  },
];
